<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Liste de commande</title>
    <link rel="stylesheet" href="index.css">
    <link rel="icon" type="image/png" sizes="16x16" href="ubuntu-logo_60ddb9.png">
  </head>
  <body>
    <header>
      <h1>Bons de commande</h1>
    </header>
    <main>
      <table>
        <caption>Liste des commandes</caption>
        <thead>
          <th>Commande</th>
          <th>Date de commande</th>
          <th>Date de livraison</th>
          <th>Statut</th>
        </thead>
        <tbody>
          <?php foreach ($result as $resultat): ?>
            <td><a href="detail.php?id=<?= $resultat["orderNumber"]; ?>"><?=  $resultat["orderNumber"]; ?></a></td>
            <td><?= $resultat["orderDate"]; ?></td>
            <td><?= $resultat["shippedDate"]; ?></td>
            <td><?= $resultat["status"]; ?></td>
          </tr>
        <?php endforeach ?>
        </tbody>
      </table>
    </main>
  </body>
</html>
