<main class="container">
  <a href="../index.php"><h1>Site de Jeux</h1></a>
  <section class="admin">
    <?php foreach ($admin as $adm): ?>
      <h1>pseudo : <?= $adm["pseudo"] ?> score : <?= $adm["score"] ?></h1>
      <a class="button" href="edit_post.php?id=<?= $adm['id'] ?>">modifier le pseudo</a>
      <a class="button" href="delete_post.php?id=<?= $adm['id'] ?>">supprimer</a>
    <?php endforeach ?>
  </section>
</main>
