
<main class="container">
  <img id="horreur" class="horreur" src="images/horeur.jpeg" alt="">
  <section >
    <canvas  id="canvas" width="800" height="700"></canvas>
    <aside class="scores">
      <h3>Les meilleurs scores!!</h3>
      <ul>
        <?php foreach ($results as $result): ?>
          <li>pseudo : <?= $result["pseudo"]?> <br>score : <?= $result["score"]?></li>
        <?php endforeach ?>
      </ul>
    </aside>
  </section>

    <form class="" action="php/form.php" method="POST">
      <label for="pseudo">pseudo</label>
      <input type="text" name="pseudo" value="">
      <input type="text" name="score" value="">
      <input type="text" name="date" value="">
      <input type="submit" name="envoyer" value="Envoyer">
    </form>
</main>
