<!-- Message de notification -->
<?php if($flashBag->hasMessages() == true): ?>
    <aside id="notice" class="notice">
        <?php foreach($flashBag->fetchMessages() as $message): ?>
            <p><?= $message ?></p>
        <?php endforeach ?>
    </aside>
<?php endif ?>
<!-- Code HTML à écrire -->

<!-- Liste des aliments -->
<table class="generic-table meal-list">
    <caption>Carte du restaurant</caption>

      <thead>
        <tr>
          <th>img</td>
          <th>nom</td>
          <th>description</td>
          <th>prix</td>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($meals as $meal): ?>
          <tr>
            <td><img src="<?=$wwwUrl?>/images/meals/<?= $meal["Photo"] ?>"></td>
            <td><?= $meal["Name"] ?></td>
            <td><?= $meal["Description"] ?></td>
            <td><?= $meal["SalePrice"] ?></td>
          </tr>
        <?php endforeach ?>
      </tbody>

</table>
